CREATE EXTERNAL TABLE TRIP (
    [TRIP_ID] NVARCHAR(1000),
    [RIDEABLE_TYPE] NVARCHAR(1000),
    [START_AT] VARCHAR(100),
    [END_AT] VARCHAR(100),
    [START_STATION_ID] NVARCHAR(1000),
    [END_STATION_ID] NVARCHAR(1000),
    [RIDER_ID] BIGINT
)
WITH (
    LOCATION = 'Source/publictrip.csv',
    DATA_SOURCE = [AZURESTORAGE],
    FILE_FORMAT = [TEXTFILEFORMAT]
)
GO

SELECT TOP 100 * FROM DBO.TRIP
GO
