CREATE EXTERNAL TABLE PAYMENT (
    [PAYMENT_ID] BIGINT,
    [DATE] VARCHAR(50),
    [AMOUNT] FLOAT,
    [RIDER_ID] BIGINT
)
WITH (
    LOCATION = 'Source/publicpayment.csv',
    DATA_SOURCE = [AZURESTORAGE],
    FILE_FORMAT = [TEXTFILEFORMAT]
)
GO

SELECT TOP 100 * FROM DBO.PAYMENT
GO

---drop external table PAYMENT