CREATE EXTERNAL TABLE RIDER (
    [RIDER_ID] BIGINT,
    [FIRSTNAME] NVARCHAR(1000),
    [LASTNAME] NVARCHAR(1000),
    [ADDRESS] NVARCHAR(1000),
    [BIRTHDAY] NVARCHAR(1000),
    [ACCOUNT_START_DATE] NVARCHAR(100),
    [ACCOUNT_END_DATE] NVARCHAR(100),
    [IS_MEMBER] BIT
)
WITH (
    LOCATION = 'Source/publicrider.csv',
    DATA_SOURCE = [AZURESTORAGE],
    FILE_FORMAT = [TEXTFILEFORMAT]
)
GO

SELECT TOP 100 * FROM DBO.RIDER
GO